# Generated by Django 4.0.7 on 2022-09-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulants',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Name', max_length=50)),
                ('first_name', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='First_Name', max_length=50, null=True)),
                ('second_name', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Second_Name', max_length=50, null=True)),
                ('age', models.IntegerField(db_column='Age')),
                ('profession', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Profession', max_length=50)),
                ('actual_state', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Actual_State', max_length=12)),
                ('date_registration', models.DateField(db_column='Date_Registration')),
                ('date_modificate', models.DateTimeField(blank=True, db_column='Date_Modificate', null=True)),
            ],
            options={
                'db_table': 'Postulants',
                'managed': False,
            },
        ),
    ]
