# Generated by Django 4.0.7 on 2022-09-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postulants',
            table='Postulants_Details',
        ),
    ]
