# Generated by Django 4.0.7 on 2022-09-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_postulants_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postulants',
            table='Postulants',
        ),
    ]
